### ISSUE TITLE
current value [] is not []

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/json_checker#27]
```python
from checker import Checker


Checker([]).validate([])


Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dkorytkin/json_checker/checker.py", line 346, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 287, in validate
    return list_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 91, in validate
    self._append_errors_or_raise(error)
  File "/home/dkorytkin/json_checker/checker.py", line 86, in _append_errors_or_raise
    raise ListCheckerError(result)
checker_exceptions.ListCheckerError: 
current value [] is not []

```

**Comment by DKorytkin** [comment]
```python
from checker import Checker
Checker([]).validate([])
Checker([]).validate([])
[]

```
