### ISSUE TITLE
AssertionError: Wrong current dict is None

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/json_checker#28]
```python
from checker import Checker
Checker({}).validate({})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c271900b0039>", line 1, in <module>
    Checker({}).validate({})
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 345, in validate
    result = checker.validate(data)
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 293, in validate
    return dict_checker.validate(data)
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 153, in validate
    self._check_dicts(data)
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 139, in _check_dicts
    assert current_dict, u'Wrong current dict is None'
AssertionError: Wrong current dict is None
```

**Comment by DKorytkin** [comment]
```python
from checker import Checker, Or
Checker(Or({'key': int}, {})).validate({})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-849abcfafcb7>", line 1, in <module>
    Checker(Or({'key': int}, {})).validate({})
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 345, in validate
    result = checker.validate(data)
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 295, in validate
    return self.expected_data.validate(data)
  File "/usr/local/lib/python2.7/dist-packages/checker.py", line 230, in validate
    assert need_data, u'Wrong data'
AssertionError: Wrong data
```
