### ISSUE TITLE
dont correct working operator Or with dicts

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/json_checker#30]
```python
from json_checker import Checker, Or, OptionalKey
ex_data = Or({'key1': int, OptionalKey('key2'): str, OptionalKey('key3'): bool}, {'test': 1})

2017-09-26 12:18:02,936 - INFO - OptionalKey(key2)
2017-09-26 12:18:02,936 - INFO - OptionalKey(key3)

Checker(ex_data).validate({'key2': 1})

2017-09-26 12:18:11,740 - INFO - Checker settings: ignore_extra_keys=False, soft=False
2017-09-26 12:18:11,740 - INFO - Run Or validation {'key2': 1}
2017-09-26 12:18:11,740 - INFO - Or expected data ({'key1': <class 'int'>, OptionalKey(key2): <class 'str'>, OptionalKey(key3): <class 'bool'>}, {'test': 1})
2017-09-26 12:18:11,740 - WARNING - Or selected dict={'test': 1}
2017-09-26 12:18:11,740 - INFO - Run dict validation {'key2': 1}
2017-09-26 12:18:11,740 - WARNING - Have error key=test result=Missing key
2017-09-26 12:18:11,740 - WARNING - Added miss keys to errors

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dkorytkin/json_checker/json_checker.py", line 388, in validate
    raise CheckerError(result)
checker_exceptions.CheckerError: 
Not valid data Or("{'key1': <class 'int'>, OptionalKey(key2): <class 'str'>, OptionalKey(key3): <class 'bool'>}", "{'test': 1}")
From key="test": Missing key
Missing keys: key2
```

> 2017-09-26 12:18:11,740 - WARNING - Or selected dict={'test': 1}

**Comment by DKorytkin** [comment]
test data:
```python
Checker(Or({'key1': int, OptionalKey('key2'): str, OptionalKey('key3'): bool}, {'test': 1})).validate({'key2': 1})
Checker(Or({'key1': int, OptionalKey('key2'): str, OptionalKey('key3'): bool}, {'test': 1})).validate({})
Checker(Or({'key1': int, OptionalKey('key2'): str, OptionalKey('key3'): bool}, {'test': 1})).validate({'test': 2})
```
