### ISSUE TITLE
Not correct unicode error message

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/json_checker#33]
for example 
```
E   From key="title": current value u'\u0411\u044e\u0434\u0436\u0435\u0442 \u043d\u0430 ProSale 4\xa0400\xa0000 \u0440\u0443\u0431.' is not 'Premium example.com'

```

**Comment by DKorytkin** [comment]
```python
from json_checker import Checker
Checker([1,2]).validate({'key1': 1})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dkorytkin/workspace/uaprom/venv/local/lib/python2.7/site-packages/json_checker.py", line 397, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/workspace/uaprom/venv/local/lib/python2.7/site-packages/json_checker.py", line 334, in validate
    return list_checker.validate(data)
  File "/home/dkorytkin/workspace/uaprom/venv/local/lib/python2.7/site-packages/json_checker.py", line 98, in validate
    self._append_errors_or_raise(error)
  File "/home/dkorytkin/workspace/uaprom/venv/local/lib/python2.7/site-packages/json_checker.py", line 92, in _append_errors_or_raise
    raise ListCheckerError(result)
ListCheckerError: 

current value (<type 'list'>, <type 'tuple'>, <type 'set'>, <type 'frozenset'>) is not {'key1': 1}

```
